Error: CSRF token mismatch logs
Since I'm not able to fix this issue, I'm uploading the "logs" I've been able to create to maybe keep working on this.